name: Publish on firestore hosting

on:
  push:
    tags:
      - "*"

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
      - name: Set version
        run: sed -i "s/VERSION/${{ steps.tag.outputs.tag }}/g" package.json
      - name: Build
        run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ROTT_DEV_E7D4D }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
